language: c
script:
    - mkdir build
    - mkdir installdir
    - cd build
    - ../aimake -i ../installdir --without=gui
compiler:
    - clang
notifications:
    irc:
        channels:
            - "chat.freenode.net#nhfourk"
